name: risk-score-fairnes
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - colorcet >= 3.0.1, < 3.1
  - joblib >= 1.1.1, < 1.2
  - matplotlib >= 3.6.0, < 3.7
  - numpy >= 1.23.1, < 1.24
  - pandas >= 1.4.4, < 1.5
  - palettable >= 3.3.0, < 3.4
  - pip
  - pyarrow >= 8.0.0
  - scikit-learn >= 1.1.1, < 1.2
  - scipy >= 1.9.1, < 1.10
  - seaborn >= 0.12.1, < 0.13
  - statsmodels >= 0.13.2, < 0.14
  - tqdm >= 4.64.1, < 5
  - xgboost >= 1.6.2, < 1.7
  - pip:
    - betacal >= 1.1.0, < 1.2
